### PR TITLE
changes for julia 0.7

### PR DESCRIPTION
**Pull request by beOn**

### CODE REVIEW

**Comment by joshbode** [comment]
Thank you for this!
I think we could try to merge #20 first, then we should rebase this PR and merge

**Comment by beOn** [comment]
Sure thing - thanks for the package :).

**Comment by jingpengw** [comment]
@beOn I have just fixed the bugs related with upgrading to Julia 0.7 and switching to HTTP.jl
would you still like to merge this? If so, could you please rebase it?

**Comment by beOn** [comment]
Arg, sorry I missed your message way back when. I think all of this has since been addressed (though I have a new issue with MbedTLS... PR coming soon). I'll close this.

**Pull request closed without merging**
