### PR TITLE
upgrade mbedtls for the sake of thread-safety

### LINKED ISSUE #34: Upgrade HTTP.jl (and CompatHelper)
This package upper bounds HTTP.jl to 0.8, while the latest release for that package is 0.9.2. It's worth upgrading the compat, since http.jl is widely used across the ecosystem.

Also, relatedly, enabling compathelper in this repo will help keep the dependencies updated

### PR DESCRIPTION
**Pull request by nlw0**
Raising MbedTLS version to 1.1.1, as discussed in #48

I was trying to write an automate test reproducing the problem more easily, but I couldn't.

Perhaps merging this we could also close #34 #35 #42, and I suspect #31 as well

### CODE REVIEW

**Comment by nlw0** [comment]
@mattBrzezinski @quinnj I still have a few important PRs open for this package for quite a while, can anyone help me?

**Comment by mattBrzezinski** [comment]
> @mattBrzezinski @quinnj I still have a few important PRs open for this package for quite a while, can anyone help me?

Hi, sorry. I personally don't have too much time for open source work anymore. These changes look good, I'd say just bump the Project version and we can merge and tag these stuff.

**Comment by nlw0** [comment]
We have now elevated the package version to `0.10.0` on another PR, can we just go ahead with this MbedTLS upgrade as well, or should the version be bumped again?

**Comment by mattBrzezinski** [comment]
> We have now elevated the package version to `0.10.0` on another PR, can we just go ahead with this MbedTLS upgrade as well, or should the version be bumped again?

`0.10.0` has been tagged, it needs a bump again

**Comment by nlw0** [comment]
bumped to 0.11.0... maybe we could take the chance to upgrade other deps? But that's really the only one in my radar

**Comment by mattBrzezinski** [comment]
> bumped to 0.11.0... maybe we could take the chance to upgrade other deps? But that's really the only one in my radar

I believe the rest are fine, since they're just specifying the minimum version? Bumping MbedTLS is specifically to fix this threading issue.

**Review by mattBrzezinski — APPROVED** [review]

**Pull request merged**
